// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA99AfsT0emv3D3pvhjdnA0W8dp4aOo7XY',
    appId: '1:227020465043:web:d789b5efadfd066139be66',
    messagingSenderId: '227020465043',
    projectId: 'qr-manager-3dabf',
    authDomain: 'qr-manager-3dabf.firebaseapp.com',
    storageBucket: 'qr-manager-3dabf.appspot.com',
    measurementId: 'G-WDS6CH765Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1k_y_jkht1vsPm9SORkcke2POIP-NF24',
    appId: '1:227020465043:android:eefeb58b589d7fa439be66',
    messagingSenderId: '227020465043',
    projectId: 'qr-manager-3dabf',
    storageBucket: 'qr-manager-3dabf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyj0GU2JlaNsnR4i5v9rNC54RS8NZ8W34',
    appId: '1:227020465043:ios:fd4366113bf791cb39be66',
    messagingSenderId: '227020465043',
    projectId: 'qr-manager-3dabf',
    storageBucket: 'qr-manager-3dabf.appspot.com',
    iosClientId: '227020465043-1r14k3jiag4tgjirkpqnvh9i9l5rp7jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrManagerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyj0GU2JlaNsnR4i5v9rNC54RS8NZ8W34',
    appId: '1:227020465043:ios:fd4366113bf791cb39be66',
    messagingSenderId: '227020465043',
    projectId: 'qr-manager-3dabf',
    storageBucket: 'qr-manager-3dabf.appspot.com',
    iosClientId: '227020465043-1r14k3jiag4tgjirkpqnvh9i9l5rp7jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrManagerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA99AfsT0emv3D3pvhjdnA0W8dp4aOo7XY',
    appId: '1:227020465043:web:1570a74118507a8c39be66',
    messagingSenderId: '227020465043',
    projectId: 'qr-manager-3dabf',
    authDomain: 'qr-manager-3dabf.firebaseapp.com',
    storageBucket: 'qr-manager-3dabf.appspot.com',
    measurementId: 'G-GHH2CGK7BL',
  );
}
